// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PizzeriaOrder.Api.Data;

#nullable disable

namespace PizzeriaOrder.Api.Migrations
{
    [DbContext(typeof(PizzeriaDbContext))]
    [Migration("20260902175443_SeedHavspizzor")]
    partial class SeedHavspizzor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PizzeriaOrder.Api.Models.Menu.MenuCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Skinkpizzor",
                            RestaurantId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Havspizzor",
                            RestaurantId = 1,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Köttfärspizzor",
                            RestaurantId = 1,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Salami & Baconpizzor",
                            RestaurantId = 1,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Ox-/Fläskfilépizzor",
                            RestaurantId = 1,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Gorgonzolapizzor",
                            RestaurantId = 1,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Mexikanska pizzor",
                            RestaurantId = 1,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Kycklingpizzor",
                            RestaurantId = 1,
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Kebabpizzor",
                            RestaurantId = 1,
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Kebab / Kyckling / Falafel",
                            RestaurantId = 1,
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Kötträtter",
                            RestaurantId = 1,
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "Grillrätter",
                            RestaurantId = 1,
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "Fiskrätter",
                            RestaurantId = 1,
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "Pastarätter",
                            RestaurantId = 1,
                            SortOrder = 14
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "Sallader",
                            RestaurantId = 1,
                            SortOrder = 15
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "Barnrätter",
                            RestaurantId = 1,
                            SortOrder = 16
                        });
                });

            modelBuilder.Entity("PizzeriaOrder.Api.Models.Menu.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MenuCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuCategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ost",
                            IsActive = true,
                            MenuCategoryId = 1,
                            Name = "Margherita",
                            Price = 100m,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Skinka",
                            IsActive = true,
                            MenuCategoryId = 1,
                            Name = "Vesuvio",
                            Price = 100m,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Skinka & ananas",
                            IsActive = true,
                            MenuCategoryId = 1,
                            Name = "Hawaii",
                            Price = 110m,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Skinka & färska champinjoner",
                            IsActive = true,
                            MenuCategoryId = 1,
                            Name = "Capricciosa",
                            Price = 110m,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Skinka & räkor",
                            IsActive = true,
                            MenuCategoryId = 1,
                            Name = "Bussola",
                            Price = 110m,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Inbakad. Skinka",
                            IsActive = true,
                            MenuCategoryId = 1,
                            Name = "Calzone",
                            Price = 110m,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Description = "Skinka, ananas, banan & curry",
                            IsActive = true,
                            MenuCategoryId = 1,
                            Name = "Florida",
                            Price = 120m,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Description = "Skinka, räkor & färska champinjoner",
                            IsActive = true,
                            MenuCategoryId = 1,
                            Name = "Bella",
                            Price = 120m,
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            Description = "Skinka, räkor, musslor, oliver, färska champinjoner & kronärtskocka",
                            IsActive = true,
                            MenuCategoryId = 1,
                            Name = "Quattro Stagioni",
                            Price = 125m,
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            Description = "Inbakad. Skinka, räkor & färska champinjoner",
                            IsActive = true,
                            MenuCategoryId = 1,
                            Name = "Calzone Special",
                            Price = 120m,
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            Description = "Dubbel deg. Skinka, räkor & färska champinjoner",
                            IsActive = true,
                            MenuCategoryId = 1,
                            Name = "Dubbel Calzone",
                            Price = 130m,
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            Description = "Skinka & tonfisk",
                            IsActive = true,
                            MenuCategoryId = 2,
                            Name = "Opera",
                            Price = 110m,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 13,
                            Description = "Tonfisk & lök",
                            IsActive = true,
                            MenuCategoryId = 2,
                            Name = "Al Tonno",
                            Price = 110m,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 14,
                            Description = "Räkor, musslor & tonfisk",
                            IsActive = true,
                            MenuCategoryId = 2,
                            Name = "Tredag",
                            Price = 120m,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 15,
                            Description = "Crème fraiche, mozzarella, rödlök, kräftstjärtar & räkor",
                            IsActive = true,
                            MenuCategoryId = 2,
                            Name = "Sjölejon & Iggon Special",
                            Price = 150m,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 16,
                            Description = "Scampi, räkor, kräftstjärtar & ruccola",
                            IsActive = true,
                            MenuCategoryId = 2,
                            Name = "Havets Läckerheter",
                            Price = 160m,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 17,
                            Description = "Champinjoner, lök, tomat, ananas, feferoni, oliver, paprika & kronärtskocka",
                            IsActive = true,
                            MenuCategoryId = 2,
                            Name = "Vegetariska",
                            Price = 130m,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 18,
                            Description = "Mozzarellaost, champinjoner, tomat & ruccolasallad",
                            IsActive = true,
                            MenuCategoryId = 2,
                            Name = "Mozzarella",
                            Price = 120m,
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("PizzeriaOrder.Api.Models.Menu.MenuItemExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceChange")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.ToTable("MenuItemExtras");
                });

            modelBuilder.Entity("PizzeriaOrder.Api.Models.Menu.MenuItemVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.ToTable("MenuItemVariants");
                });

            modelBuilder.Entity("PizzeriaOrder.Api.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Tittmyrvägen 1",
                            City = "Gävle",
                            CreatedAtUtc = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Trödje Pizzeria",
                            Phone = "026-16 14 11",
                            PostalCode = "805 96"
                        });
                });

            modelBuilder.Entity("PizzeriaOrder.Api.Models.Menu.MenuCategory", b =>
                {
                    b.HasOne("PizzeriaOrder.Api.Models.Restaurant", "Restaurant")
                        .WithMany("MenuCategories")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("PizzeriaOrder.Api.Models.Menu.MenuItem", b =>
                {
                    b.HasOne("PizzeriaOrder.Api.Models.Menu.MenuCategory", "MenuCategory")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuCategory");
                });

            modelBuilder.Entity("PizzeriaOrder.Api.Models.Menu.MenuItemExtra", b =>
                {
                    b.HasOne("PizzeriaOrder.Api.Models.Menu.MenuItem", "MenuItem")
                        .WithMany("Extras")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("PizzeriaOrder.Api.Models.Menu.MenuItemVariant", b =>
                {
                    b.HasOne("PizzeriaOrder.Api.Models.Menu.MenuItem", "MenuItem")
                        .WithMany("Variants")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("PizzeriaOrder.Api.Models.Menu.MenuCategory", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("PizzeriaOrder.Api.Models.Menu.MenuItem", b =>
                {
                    b.Navigation("Extras");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("PizzeriaOrder.Api.Models.Restaurant", b =>
                {
                    b.Navigation("MenuCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
